TEMP1 = $02 ; ZP
TEMP2 = $03 ; ZP
TEMP3 = $04 ; ZP
TEMP4 = $05 ; ZP
TEMP5 = $06 ; ZP

COLLISION_LOOKUP = $08   ; ZP + 1
COLLISION_X      = $0A   ; ZP
COLLISION_Y      = $0B   ; ZP

JOY_ZP =    $0C ; ZP

PLAYER_STATE    = $0D ; ZP
PL_TURBO        = $0E ; ZP

X_OFFSET = $0F  ; ZP
Y_OFFSET = $10  ; ZP

POINT_COUNTER = $11 ; ZP
POINT_TYPE =    $12 ; ZP
POINT_VALUE =   $13 ; ZP

GAME_STATE =    $14 ; ZP
CODE_FLAG  =    $15

COUNTER =       $16
MILISEC =       $17
SECONDS =       $18

IRQ_A   =       $19
IRQ_X   =       $1A
IRQ_Y   =       $1B

POINTER1 =  $1C
POINTER2 =  $1E
POINTER3 =  $20
POINTER4 =  $22

ACTIVE_ENEMIES      = $24
ENTITY_TO_UPDATE    = $25 ; ZP

COLLISION_LOOKUP2   = $26
COLOR_LOOKUP        = $28
COLOR_LOOKUP2       = $2A


