TEMP1 = $02 ; ZP
TEMP2 = $03 ; ZP
TEMP3 = $04 ; ZP
TEMP4 = $05 ; ZP
TEMP5 = $06 ; ZP

ENTITY_TO_UPDATE = $07 ; ZP

COLLISION_LOOKUP = $08   ; ZP + 1
COLLISION_X      = $0A   ; ZP
COLLISION_Y      = $0B   ; ZP

JOY_ZP =    $0C ; ZP

PL_DIR          = $0D ; ZP
PL_TURBO        = $0E ; ZP
PLAYER_STATE    = $21 ; ZP

X_OFFSET = $0F  ; ZP
Y_OFFSET = $10  ; ZP

POINT_COUNTER = $11 ; ZP
POINT_TYPE =    $12 ; ZP
POINT_VALUE =   $13 ; ZP
GAME_STATE =    $14 ; ZP

COUNTER =       $15

POINTER1 =  $1A
POINTER2 =  $1C
POINTER3 =  $1E
POINTER4 =  $20
POINTER5 =  $22
POINTER6 =  $24
POINTER7 =  $26
POINTER8 =  $28
POINTER9 =  $2A

ACTIVE_ENEMYES = $2C

