TEMP1 = $02 ; ZP
TEMP2 = $03 ; ZP
TEMP3 = $04 ; ZP
TEMP4 = $05 ; ZP
TEMP5 = $06 ; ZP

COLLISION_LOOKUP = $08   ; ZP + 1
COLLISION_X      = $0A   ; ZP
COLLISION_Y      = $0B   ; ZP

JOY_ZP =    $0C ; ZP

PLAYER_STATE    = $0D ; ZP
PL_TURBO        = $0E ; ZP

X_OFFSET = $0F  ; ZP
Y_OFFSET = $10  ; ZP

POINT_COUNTER = $11 ; ZP
POINT_TYPE =    $12 ; ZP
POINT_VALUE =   $13 ; ZP

GAME_STATE =    $14 ; ZP
CODE_FLAG  =    $27

COUNTER =       $24
MILISEC =       $25
SECONDS =       $26

IRQ_A   =       $28
IRQ_X   =       $29
IRQ_Y   =       $2A
POINTER1 =  $1A
POINTER2 =  $1C
POINTER3 =  $1E
POINTER4 =  $20

ACTIVE_ENEMIES = $22
ENTITY_TO_UPDATE = $23 ; ZP

COLOR_LOOKUP = $2C
